[package]
name = "cmd-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.8.0"
rand = "0.8.5"
smol = "2.0.0"
tokio = { version = "1.36.0", features = ["full"] }
